### ISSUE TITLE
TravisCI automation script template

### ISSUE THREAD

**Issue by humorless** [cryogen-project/cryogen#176]
Hi, 

I use `cryogen` with TravisCI. 
Here is my `.travis.yml`. 
I guess someone would happy to use it together with static site generation. 
```
# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/clojure/
# https://docs.travis-ci.com/user/customizing-the-build/
dist: xenial
language: clojure

before_script:
    - lein clean

# script - run the build script
script:
    - lein run

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: resources/public
  target_branch: master  # branch contains blog content
  on:
    branch: code  # branch contains Cryogen generator code
```
